#!/usr/bin/env bash

if [ $1 = "install" ]
then
    cargo build
elif [ $1 = "build" ]
then
    cargo build
elif [ $1 = "test" ]
then
    cargo test
    # this is not going to work
else
    cargo run -- $1
fi